run:
  timeout: 5m
  skip-files: []

linters-settings:
  govet:
    check-shadowing: true
  gocyclo:
    min-complexity: 20
  goconst:
    min-len: 5
    min-occurrences: 3
  misspell:
    locale: US
  funlen:
    lines: -1
    statements: 50
  godox:
    keywords:
      - FIXME
  depguard:
    rules:
      main:
        deny:
          - pkg: "github.com/instana/testify"
            desc: not allowed
          - pkg: "github.com/pkg/errors"
            desc: Should be replaced by standard lib errors package
  testifylint:
    enable:
      - bool-compare
      - compares
      - empty
      - error-is-as
      - error-nil
      - expected-actual
      - float-compare
      - len
      - suite-dont-use-pkg
      - suite-extra-assert-call
      - suite-thelper

linters:
  enable-all: true
  disable:
    - deadcode # deprecated
    - exhaustivestruct # deprecated
    - golint # deprecated
    - ifshort # deprecated
    - interfacer # deprecated
    - maligned # deprecated
    - nosnakecase # deprecated
    - scopelint # deprecated
    - structcheck # deprecated
    - varcheck # deprecated
    - sqlclosecheck # not relevant (SQL)
    - rowserrcheck # not relevant (SQL)
    - execinquery # not relevant (SQL)
    - cyclop # duplicate of gocyclo
    - lll
    - dupl
    - wsl
    - nlreturn
    - gomnd
    - goerr113
    - wrapcheck
    - exhaustive
    - exhaustruct
    - testpackage
    - tparallel
    - paralleltest
    - prealloc
    - ifshort
    - forcetypeassert
    - varnamelen
    - nilnil
    - ireturn
    - nonamedreturns

issues:
  exclude-use-default: false
  max-per-linter: 0
  max-same-issues: 0
  exclude:
    - "Error return value of .((os\\.)?std(out|err)\\..*|.*Close|.*Flush|os\\.Remove(All)?|.*printf?|os\\.(Un)?Setenv). is not checked"
    - "exported (type|method|function) (.+) should have comment or be unexported"
  exclude-rules:
    - path: (.+)_test.go
      linters:
        - funlen
        - goconst
