version: "2"

formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports

linters:
  default: all
  disable:
    - cyclop # duplicate of gocyclo
    - dupl
    - err113
    - exhaustive
    - exhaustruct
    - forcetypeassert
    - ireturn
    - lll
    - mnd
    - nilnil
    - nlreturn
    - nonamedreturns
    - paralleltest
    - prealloc
    - rowserrcheck # not relevant (SQL)
    - sqlclosecheck # not relevant (SQL)
    - testpackage
    - tparallel
    - varnamelen
    - wrapcheck
    - wsl
  settings:
    depguard:
      rules:
        main:
          deny:
            - pkg: github.com/instana/testify
              desc: not allowed
            - pkg: github.com/pkg/errors
              desc: Should be replaced by standard lib errors package
    funlen:
      lines: -1
      statements: 50
    goconst:
      min-len: 5
      min-occurrences: 3
    gocyclo:
      min-complexity: 20
    godox:
      keywords:
        - FIXME
    govet:
      enable:
        - shadow
    misspell:
      locale: US
    perfsprint:
      err-error: true
      errorf: true
      sprintf1: true
      strconcat: false
    testifylint:
      disable:
        - require-error
        - go-require
  exclusions:
    presets:
      - std-error-handling
      - comments
    rules:
      - linters:
          - funlen
          - goconst
        path: (.+)_test.go

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
